services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

  gateway:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    depends_on:
      - auth-service
      - blocks-service
    networks:
      - app-network

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    env_file:
      - ./auth-service/.env
    networks:
      - app-network

  blocks-service:
    build:
      context: ./blocks-service
      dockerfile: Dockerfile
    env_file:
      - ./blocks-service/.env
    depends_on:
      - redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge