export const abi = [
  "constructor()",
  "event BlockBought(uint256 indexed blockId, address indexed buyer, uint256 price)",
  "event BlockPriceSet(uint256 indexed blockId, uint256 newPrice)",
  "event BlockSold(uint256 indexed blockId, address indexed seller, uint256 price)",
  "event ColorChanged(uint256 indexed blockId, uint8 newColor)",
  "event OwnershipTransferred(address indexed previousOwner, address indexed newOwner)",
  "function GRID_SIZE() view returns (uint256)",
  "function TOTAL_BLOCKS() view returns (uint256)",
  "function buyBlock(uint256 blockId) payable",
  "function buyFromUser(uint256 blockId) payable",
  "function buyMultipleBlocks(uint256[] memory blockIds) payable",
  "function defaultPrice() view returns (uint256)",
  "function getAllBlocksInfo(uint256 startId, uint256 endId) view returns (tuple(address blockAddress, address owner, uint8 color, uint256 price)[] memory)",
  "function getBlockInfo(uint256 blockId) view returns (tuple(address blockAddress, address owner, uint8 color, uint256 price))",
  "function getBlockPrice(uint256 blockId) view returns (uint256)",
  "function mintPrice() view returns (uint256)",
  "function owner() view returns (address)",
  "function ownerOf(uint256 tokenId) view returns (address)",
  "function renounceOwnership()",
  "function sellBlock(uint256 blockId, uint256 price)",
  "function setBlockPrice(uint256 blockId, uint256 newPrice)",
  "function setColor(uint256 blockId, uint8 color)",
  "function setMintPrice(uint256 newPrice)",
  "function transferOwnership(address newOwner)",
  "function withdraw()"
];
